export const events = [
  {
    id: 'focus',
    title: 'Focus time',
    time: '8:00 – 9:30 AM',
    start: 0,
    duration: 90,
    tone: 'violet',
  },
  {
    id: 'review',
    title: 'Design review',
    time: '9:30 – 10:30 AM',
    start: 90,
    duration: 60,
    tone: 'blue',
  },
  {
    id: 'break',
    title: 'Break',
    time: '11:00 – 11:15 AM',
    start: 180,
    duration: 15,
    tone: 'violet',
  },
  {
    id: 'call',
    title: 'Customer call',
    time: '12:00 – 1:00 PM',
    start: 240,
    duration: 60,
    tone: 'coral',
  },
  {
    id: 'launch',
    title: 'Launch plan',
    time: '1:30 – 3:00 PM',
    start: 330,
    duration: 90,
    tone: 'blue',
  },
  {
    id: 'retro',
    title: 'Team retro',
    time: '3:30 – 4:15 PM',
    start: 450,
    duration: 45,
    tone: 'amber',
  },
  {
    id: 'planning',
    title: 'Weekly planning',
    time: '5:00 – 5:45 PM',
    start: 540,
    duration: 45,
    tone: 'violet',
  },
];

export const initialTasks = [
  { id: 'feedback', title: 'Design feedback', meta: 'Due today', tone: 'violet' },
  { id: 'email', title: 'Email Miguel', meta: 'Due today', tone: 'blue' },
  { id: 'deck', title: 'Prepare deck', meta: 'Due today', tone: 'amber' },
  { id: 'gift', title: 'Buy gift', meta: 'No due date', tone: 'mint' },
];

export const initialSubtasks = [
  { id: 'messages', title: 'Draft key messages', duration: '30m', done: true },
  { id: 'timeline', title: 'Outline timeline', duration: '20m', done: false },
  { id: 'audience', title: 'Identify audience', duration: '15m', done: false },
  { id: 'share', title: 'Share draft with team', duration: '10m', done: false },
];

export const initialNotes = [
  {
    id: 'launch-plan',
    category: 'Planning',
    title: 'Launch plan',
    excerpt: 'Finalizing timelines and aligning on priorities for a smooth launch next week.',
    timestamp: 'Today, 2:28 PM',
    tone: 'violet',
  },
  {
    id: 'focus-choice',
    category: 'Ideas',
    title: 'Focus is a choice',
    excerpt: 'Protect your focus like it’s your most valuable asset. It shapes everything.',
    timestamp: 'Today, 9:12 AM',
    tone: 'blue',
  },
  {
    id: 'design-feedback',
    category: 'Work',
    title: 'Design feedback',
    excerpt: 'Loved the direction. Small tweaks to spacing and hierarchy will make a big impact.',
    timestamp: 'Yesterday, 4:40 PM',
    tone: 'amber',
  },
  {
    id: 'gratitude',
    category: 'Personal',
    title: 'Gratitude',
    excerpt: 'Grateful for the small wins, meaningful conversations, and moments of calm.',
    timestamp: 'Yesterday, 9:07 PM',
    tone: 'mint',
  },
  {
    id: 'deep-work',
    category: 'Focus',
    title: 'Deep work block',
    excerpt: 'Morning is my best window for deep work. No meetings, no distractions.',
    timestamp: 'Yesterday, 8:30 AM',
    tone: 'violet',
  },
  {
    id: 'design-systems',
    category: 'Learning',
    title: 'Design systems',
    excerpt: 'Consistency creates clarity. Systems scale ideas into beautiful experiences.',
    timestamp: 'Sep 2, 6:15 PM',
    tone: 'violet',
  },
  {
    id: 'customer-delight',
    category: 'Ideas',
    title: 'Customer delight',
    excerpt: 'The little details are the big difference. Make the experience feel effortless.',
    timestamp: 'Sep 2, 11:20 AM',
    tone: 'blue',
  },
  {
    id: 'team-retro',
    category: 'Work',
    title: 'Team retro',
    excerpt: 'Celebrate wins, learn openly, and keep raising the bar together.',
    timestamp: 'Sep 1, 3:45 PM',
    tone: 'amber',
  },
  {
    id: 'evening-reset',
    category: 'Personal',
    title: 'Evening reset',
    excerpt: 'Slow down, reflect, and prepare for a better tomorrow.',
    timestamp: 'Sep 1, 9:30 PM',
    tone: 'mint',
  },
];
