package integrations

import (
 "encoding/json"
 "errors"
 "os"
 "path/filepath"
 "reflect"
 "floe/server/internal/connections"
 "floe/server/internal/credentials"
 "floe/server/internal/storage"
 "floe/server/internal/trust"
)

type attemptRecord struct { ID,ClientID,PersonID,DeviceID,ConnectorID string; Record connections.Record; Status AuthorizationState; AuthorizationURL,UserCode,ErrorCode string; CreatedAt int64;Revision uint64;Started bool;CatalogRevision uint64;RequestedScope map[string]any }
type cleanupRecord struct { ID string; Ticket *trust.CleanupTicket; Records []connections.Record; RuntimeDone map[string]bool; VaultDone map[string]bool }
type disconnectOperation struct { OperationID,ClientID,PersonID,DeviceID,ConnectorID,ConnectionID string;ConnectionRevision uint64;CleanupState string }
type diskState struct { SchemaVersion int `json:"schema_version"`; Revision uint64 `json:"revision"`; Connections map[string]connections.Record `json:"connections"`; Attempts map[string]attemptRecord `json:"attempts"`; Cleanup map[string]cleanupRecord `json:"cleanup"`; Receipts map[string]trust.CleanupReceipt `json:"receipts"`;Disconnects map[string]disconnectOperation `json:"disconnects"` }
func initialState()diskState{return diskState{1,1,map[string]connections.Record{},map[string]attemptRecord{},map[string]cleanupRecord{},map[string]trust.CleanupReceipt{},map[string]disconnectOperation{}}}
func clone(st diskState)diskState{out:=initialState();out.Revision=st.Revision;for k,r:=range st.Connections{out.Connections[k]=cloneRecord(r)};for k,a:=range st.Attempts{a.Record=cloneRecord(a.Record);a.RequestedScope=connections.CloneConnectorScope(a.RequestedScope);out.Attempts[k]=a};for k,c:=range st.Cleanup{c.Records=append([]connections.Record(nil),c.Records...);for i:=range c.Records{c.Records[i]=cloneRecord(c.Records[i])};rd,vd:=map[string]bool{},map[string]bool{};for k,v:=range c.RuntimeDone{rd[k]=v};for k,v:=range c.VaultDone{vd[k]=v};c.RuntimeDone,c.VaultDone=rd,vd;if c.Ticket!=nil{t:=*c.Ticket;c.Ticket=&t};out.Cleanup[k]=c};for k,v:=range st.Receipts{out.Receipts[k]=v};for k,v:=range st.Disconnects{out.Disconnects[k]=v};return out}
func cloneRecord(r connections.Record)connections.Record{r.Scope=connections.CloneConnectorScope(r.Scope);if r.Device!=nil{d:=*r.Device;r.Device=&d};return r}
func binding(r connections.Record)CredentialBinding{return CredentialBinding{r.Credential,r.ConnectionID,r.PersonID,r.Incarnation,1}}
func validateRecord(r connections.Record)bool{d,ok:=connections.DefinitionFor(r.ConnectorID);if !ok||!trust.ValidID(r.ConnectionID)||!trust.ValidID(r.PersonID)||!trust.ValidID(r.Incarnation)||r.Revision==0||r.Epoch==0||r.Device!=nil&&!trust.ValidDevice(r.Device.DeviceID){return false};if canonical,err:=connections.ValidatedConnectorScope(d,r.Scope);err!=nil||!reflect.DeepEqual(canonical,r.Scope){return false};namespace:=d.CredentialName;if namespace==""{namespace=d.OAuthCredential};slot,err:=credentials.ConnectionName(namespace,r.ConnectionID,r.PersonID);return err==nil&&slot==r.Credential}
func readState(directory string)(diskState,error){st:=initialState();path:=filepath.Join(directory,"integrations.json");data,err:=storage.ReadPrivate(path,2<<20);if os.IsNotExist(err){return st,nil};if err!=nil||trust.DecodeStrict(data,&st,2<<20,32)!=nil||st.SchemaVersion!=1||st.Revision==0||st.Connections==nil||st.Attempts==nil||st.Cleanup==nil||st.Receipts==nil||st.Disconnects==nil||len(st.Connections)>9||len(st.Attempts)>64||len(st.Cleanup)>64||len(st.Receipts)>128||len(st.Disconnects)>256{return st,errors.New("integration state unavailable")};owned:=map[string]bool{};for id,r:=range st.Connections{key:=r.PersonID+"/"+r.ConnectorID;if id!=r.ConnectionID||!validateRecord(r)||owned[key]{return st,errors.New("invalid integration state")};owned[key]=true};for id,a:=range st.Attempts{if id!=a.ID||!trust.ValidID(id)||!trust.ValidID(a.ClientID)||a.PersonID!=a.Record.PersonID||!trust.ValidDevice(a.DeviceID)||!(validateRecord(a.Record)||(a.Status==AwaitingUser||a.Status==Cancelled||a.Status==Failed)&&!a.Started&&len(a.Record.Scope)==0&&validAttemptIdentity(a.Record))||a.RequestedScope==nil||a.CatalogRevision==0||a.ConnectorID!=a.Record.ConnectorID||a.CreatedAt<=0||a.Revision==0||a.Status!=Pending&&a.Status!=Connected&&a.Status!=Failed&&a.Status!=AwaitingUser&&a.Status!=Cancelled{return st,errors.New("invalid integration attempt")}};for id,c:=range st.Cleanup{if id!=c.ID||!trust.ValidID(id)||c.RuntimeDone==nil||c.VaultDone==nil{return st,errors.New("invalid integration cleanup")};for _,r:=range c.Records{if !validateRecord(r){return st,errors.New("invalid integration cleanup")}}};for id,o:=range st.Disconnects{if id!=o.OperationID||!trust.ValidID(id)||!trust.ValidID(o.ClientID)||!trust.ValidID(o.PersonID)||!trust.ValidDevice(o.DeviceID)||!trust.ValidID(o.ConnectionID)||o.ConnectionRevision==0||o.CleanupState!="pending"&&o.CleanupState!="completed"{return st,errors.New("invalid disconnect operation")}};return st,nil}
func(s *Service) persist(st diskState)error{if s.unavailable{return errors.New("integration persistence uncertain")};st.Revision=s.state.Revision+1;data,err:=json.Marshal(st);if err!=nil{return err};err=storage.WritePrivate(filepath.Join(s.directory,"integrations.json"),data);if storage.IsIndeterminate(err){s.unavailable=true};if err!=nil{return errors.New("integration persistence unavailable")};s.state=st;return nil}

func validAttemptIdentity(r connections.Record)bool{d,ok:=connections.DefinitionFor(r.ConnectorID);if !ok||!trust.ValidID(r.ConnectionID)||!trust.ValidID(r.PersonID)||!trust.ValidID(r.Incarnation)||r.Revision!=1||r.Epoch!=1{return false};namespace:=d.CredentialName;if namespace==""{namespace=d.OAuthCredential};slot,err:=credentials.ConnectionName(namespace,r.ConnectionID,r.PersonID);return err==nil&&slot==r.Credential}
